### ISSUE TITLE
[Visual Bug] Guild Bank + Item Tooltip's

### ISSUE THREAD

**Issue by Medivha** [jrob8577/AuctionatorAddon#58] opened 2015-12-24 17:12 UTC
I copy paste the text from the TSM website, they send me to you!

Hi Tradeskillmaster Team,

I have a visual bug on the tooltip's from items when i hover them if the Guild Bank is open! It shows some Tooltip parts multiple times and disapear so it flickers.
And it is only when i have ArkInventory + TSM or Auctinator + TSM activated and the Guild Bank is open.

When i have one of the following setups i have no problems:
TSM alone,
ARkInv alone,
Auctionator alone 
or ArkInv + Auctionator

I was assuming, TSM have some confliction issues with these addons and it is on TSM's side.

http://imgur.com/4dSHVtt (with ArkInv+TSM)

on ArkInv it is only in my inventory
http://imgur.com/2yL8yFU (with Auctionator+TSM)

on Auctionator it is on every tooltip, also when i hover something else and in this case it expands endless
TSM Versions http://imgur.com/eznbBe0
ArkInventory 3.05.12
Auctionator 3.2.6

All other Addons was disabled and i enabled only the combinations mentioned above.
I tested it with BugGrabber and BugSack but i dont got any LUA error!

So because it always appears when TSM is involved i post it here first and when it is not on your side i move to the ArkInventory and Auctionator sides.

So thanks for reading and i wish you all Merry Christmas!

Original TSM post:
http://stormspire.net/tradeskillmaster-addon/17976-%5Bvisual-bug%5D-guild-bank-item-tooltips.html

**Comment by jrob8577** [comment] 2015-12-28 05:51
It looks like this is an issue with how TSM is processing battle pets in the guildbank.  Here's my response on [curse](http://www.curse.com/addons/wow/auctionator#c5802):

I've managed to reproduce.  The TSM author is using a special function (that is normally used to *set* tooltip information for a guild bank item) to *get* information from a guild tab that Auctionator is hooking to display auction information.  In TSM, this function is called over and over again while the guild bank is open, resulting in the tooltip spam that you're seeing.

One possible fix for this in Auctionator is to disable the tooltips in the guild bank, which I don't think is a great solution to avoid conflict with TSM (which, BTW, would conflict with any other addon that attempts to add tooltip information to items in the guild bank).  I'll see if I can put together a patch for TSM, but if I'm reading that code correctly, any patch I came up with would change the way TSM represents pet IDs, which would probably have other repercussions in the addon.  :-(

I'll file this bug for myself and see if I can think of another solution in the Auctionator codebase (I can conceive of a way, but it would involve a lot of work jsut to get around one line of code in someone else's addon...).

**Comment by jrob8577** [comment] 2015-12-28 06:22
Thinking about this a little more, I'll add a flag in the options to allow users to turn off Auctionator guild bank integration, so at least both addons will be useable...

**Comment by jrob8577** [comment] 2015-12-28 07:22
I've added a toggle in 3.2.7, hope to release in the next few days.

**Closed by jrob8577** 2015-12-28 07:22 UTC
Labels: enhancement

**Comment by Medivha** [comment] 2015-12-28 14:11
thanks for working on a workaround! i posted our respond also on the tsm forum in hope tsm can help with it

**Comment by Bart39** [comment] 2015-12-28 15:11
Bart from the TSM team here, unfortunately i can't think of any other way to get battle pet info from the guild vault, if anyone knows of another way other than using GameTooltip:SetGuildBankItem then we would be glad to consider it

**Comment by jrob8577** [comment] 2015-12-28 16:30
Hey @Bart39 !  

I've played with a few things, but no luck.  The problem is that Auctionator (and apparently a few other addons) use `hooksecurefunc` to associate some post processing with the `SetGuildBankItem`.  When TSM calls:
```lua
local speciesID = GameTooltip:SetGuildBankItem(bag, slot)
```
it causes our hooks to execute.  Since TSM does the guild bank scanning in the OnUpdate, this gets called many times.  

Maybe we could throttle the guild bank processing so it's not called in every OnUpdate loop? It would still probably flash the "tooltip spam", but I'd be curious to see if it allowed tool tips to display correctly in between.  

I've also been trying to figure out if there's another way to get pet information from the Pet Cage itemlinks returned by the guild bank API...  It's a little frustrating that blizzard treats items differently in different bag locations :frowning:  ... I'm curious if there's information that can be obtained by the uniqueID segment of the itemstring for a Pet Cage item, but I'm not seeing a pattern yet....

**Comment by arkayenro** [comment] 2016-07-04 01:57
possibly a silly question but why is the TSM code touching GameToolip at all for "scanning" purposes?

create your own private tooltip (inherit the template) and use that instead, that way you can set that as often as you need to and no one else will care

setting the GameTooltip (even if you dont show it) and obviously everyone who has hooked it will get their functions called
